name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  clone-and-install:
    strategy:
      matrix:
        os: [ubuntu, macos]
    runs-on: ${{ matrix.os }}-latest
    env:
      CODESPACES: true
    steps:
      - uses: actions/checkout@v4
      - run: ./install.sh
      - name: chezmoi data
        run: '"$HOME/.local/bin/chezmoi" data'
